services:
  moriicoffee.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: moriicoffee.database
    environment:
      MSSQL_DATABASE: MoriiCoffeeDB
      MSSQL_SA_PASSWORD: "MoriiCoffee@123~"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - moriicoffee_sqlserver_data:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'MoriiCoffee@123~' -Q 'SELECT 1' -C -b"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  moriicoffee.minio:
    image: minio/minio:latest
    container_name: moriicoffee.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    volumes:
      - moriicoffee_minio_data:/data
      - moriicoffee_minio_config:/root/.minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

networks:
  default:
    name: moriicoffee_network
    driver: bridge

volumes:
  moriicoffee_sqlserver_data:
    name: moriicoffee_sqlserver_data
  moriicoffee_minio_data:
    name: moriicoffee_minio_data
  moriicoffee_minio_config:
    name: moriicoffee_minio_config
