services:
  moriicoffee.api:
    image: moriicoffee.api
    container_name: moriicoffee.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnectionString=Host=moriicoffee.database;Port=5432;Database=MoriiCoffeeDb;Username=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__CachingConnectionString=moriicoffee.redis:6379,abortConnect=false
    depends_on:
      moriicoffee.database:
        condition: service_healthy
      moriicoffee.minio:
        condition: service_started
      moriicoffee.redis:
        condition: service_started
    ports:
      - "8002:80"
    build:
      context: ..
      dockerfile: source/MoriiCoffee.Presentation/Dockerfile
    restart: on-failure

networks:
  default:
    name: moriicoffee_network
    driver: bridge
