namespace MoriiCoffee.Application.SeedWork.Abstractions;

/// <summary>Service for sending transactional emails such as welcome and password reset messages.</summary>
public interface IEmailService
{
    /// <summary>Sends a welcome email to a newly registered user at the given address.</summary>
    Task SendWelcomeEmailAsync(string to, string name);

    /// <summary>Sends a password-reset email containing the one-time token generated by Identity.</summary>
    Task SendPasswordResetEmailAsync(string to, string token);
}
